'use strict'

const colorList = [
          ['indainred'],
          ['lightcoral'],
          ['salmon'],
          ['darksalmon'],
          ['lightsalmon'],
          ['crimson'],
          ['red'],
          ['firebrick'],
          ['darkred'],
          ['pink'],
          ['lightpink'],
          ['hotpink'],
          ['deeppink'],
          ['mediumvioletred'],
          ['palevioletred'],
          ['coral'],
          ['tomato'],
          ['orangered'],
          ['darkorange'],
          ['orange'],
          ['gold'],
          ['yellow'],
          ['lightyellow'],
          ['lemonchiffon'],
          ['lightgoldenrodyellow'],
          ['papayawhip'],
          ['mocassin'],
          ['peachpuff'],
          ['palegordenrod'],
          ['lavender'],
          ['thistle'],
          ['plum'],
          ['violet'],
          ['orchid'],
          ['fuchsia', 'magenta'],
          ['mediumorchid'],
          ['mediumpurple'],
          ['blueviolet'],
          ['darkviolet'],
          ['darkorchid'],
          ['darkmagenta'],
          ['rebeccapurple'],
          ['purple'],
          ['indigo'],
          ['slateblue'],
          ['darkslateblue'],
          ['cornsilk'],
          ['blanchedalmond'],
          ['bisque'],
          ['navajowhite'],
          ['wheat'],
          ['burlywood'],
          ['tan'],
          ['rosybrown'],
          ['sandybrown'],
          ['goldenrod'],
          ['darkgoldenrod'],
          ['peru'],
          ['chocolate'],
          ['saddlebrown'],
          ['sienna'],
          ['brown'],
          ['maroon'],
          ['greenyellow'],
          ['cartreuse'],
          ['lawngreen'],
          ['lime'],
          ['limegreen'],
          ['palegreen'],
          ['lightgreen'],
          ['mediumspringgreen'],
          ['springgreen'],
          ['mediumseagreen'],
          ['seagreen'],
          ['forestgreen'],
          ['green'],
          ['darkgreen'],
          ['yellowgreen'],
          ['olivedrab'],
          ['olive'],
          ['darkolivegreen'],
          ['mediumaquamarine'],
          ['darkseagreen'],
          ['lightseagreen'],
          ['darkcyan'],
          ['teal'],
          ['auqa', 'cyan'],
          ['lightcyan'],
          ['paleturquoise'],
          ['aquamarine'],
          ['turquoise'],
          ['mediumturquoise'],
          ['darkturquoise'],
          ['cadetblue'],
          ['steelblue'],
          ['lightsteelblue'],
          ['powderblue'],
          ['lightblue'],
          ['skyblue'],
          ['lightskyblue'],
          ['deepskyblue'],
          ['dodgerblue'],
          ['cornflowerblue'],
          ['mediumslateblue'],
          ['royalblue'],
          ['blue'],
          ['mediumblue'],
          ['darkblue'],
          ['navy'],
          ['midnightblue'],
          ['white'],
          ['snow'],
          ['honeydew'],
          ['mintcream'],
          ['azure'],
          ['aliseblue'],
          ['ghostwhite'],
          ['whitesmoke'],
          ['seashell'],
          ['beige'],
          ['oldlace'],
          ['floralwhite'],
          ['ivory'],
          ['antiquewhite'],
          ['linen'],
          ['lavenredblush'],
          ['mistyrose'],
          ['gainsboro'],
          ['lightgray', 'lightgrey'],
          ['silver'],
          ['darkgray', 'darkgrey'],
          ['gray', 'grey'],
          ['dimgray', 'dimgrey'],
          ['lightslategray', 'lightslategrey'],
          ['slategray', 'slategrey'],
          ['darkslategray', 'darkslategrey'],
          ['black']
        ];

const colorRect = document.querySelector('.js-color-rect');
const checkButton = document.querySelector('.js-check');

function setColor() {
  let randomColorIndex = Math.round(Math.random() * (colorList.length - 1));
  console.log(randomColorIndex)
  colorRect.style.backgroundColor = colorList[randomColorIndex][0];
}

window.onload = setColor;
checkButton.onclick = setColor;
